"" TODO
" 1. Update nerdtree with cd!  
"     1.b And update nerdtree when a new file is added (:w)
" 2. Better Nerdtree mappings (check for empty filename, etc)
" 3. Delete MyDiff() in this file
" 4. Quick Switch, Multi-select. <C-[1-9]> remembers selection
"    1s2 switches selection 1 and 2
"    123sc applies c to the selections 1 2 and 3
" 5. Tab = 4spaces

"" Vim settings, rather than Vi settings (must be first)
set nocompatible

"Unicode Support
scriptencoding utf-8
set encoding=utf-8

"" Execute vanilla (for windows) scripts
source $VIMRUNTIME/vimrc_example.vim
" source $VIMRUNTIME/mswin.vim " windows shortcuts.
" NOTE: mswin.vim has been renamed to [ORIGINAL]mswin.vim

"" Personal Settings
if has("gui_running")
  if getcwd()=="C:\\windows\\System32"
    cd C:\Users\Daniel
  endif
endif

"" Encoding -- Again? I don't know, it doesn't work otherwise
scriptencoding utf-8
set encoding=utf-8

"" Behavior
"autocmd BufRead * loadview
"autocmd BufWritePost * mkview
autocmd BufWritePost * silent execute '! if [ -f tags ]; then ctags -R .; fi'
set tags=./tags;/
set backup
set backupdir=$HOME\\vimfiles\\backups,c:/tmp,c:/temp
set undofile
set undodir=$HOME\\vimfiles\\backups,c:/tmp,c:/temp
behave xterm
set backspace=indent,eol,start
set fdm=marker
set tabstop=2
set shiftwidth=2
set autoindent
set expandtab
set linebreak
set nowrap
set wildmenu
set incsearch
set hlsearch

"" force yourself to stop using the arrow keys:
map <up>    <nop>
map <down>  <nop>
map <left>  <nop>
map <right> <nop>
" harder
imap <up>    <nop>
imap <down>  <nop>
imap <left>  <nop>
imap <right> <nop>

"" GUI
if has("gui_running")
set laststatus=2
set lines=45
set columns=112
color twilight
let g:sessionfontsize=8
set guifont=Consolas:h8:cANSI "remember to also change the font keymaps!
set guioptions=eg
endif
syntax on
set listchars=trail:·,precedes:«,extends:»,tab:▸\ ,eol:▾
set whichwrap+=<,>,[,]
set nu
set rnu
set list
set display +=lastline
autocmd FileType c,cpp,java,scala set colorcolumn=80
autocmd FileType vim              set colorcolumn=80
autocmd FileType text             set colorcolumn=0
hi ColorColumn ctermbg=darkgrey guibg=#333333
" SECTION: GUI Functions {{{1
function! ToggleFullscreen()
	if matchstr(&guioptions,"m")!=""
		set guioptions -=b
		set guioptions -=m
		set guioptions -=r
		set guioptions -=L
		return "Fullscreen On"
	else
		set guioptions +=b
		set guioptions +=m
		set guioptions +=r
		set guioptions +=L
		return "Fullscreen Off"
	endif
endfunction
function! ToggleDocType()
	if &l:wrap
		setl nowrap
		setl nu
        setl rnu
		setl list
        setl textwidth=78
		return "Code Document"
	else
		setl wrap
		setl nonu
        setl nornu
		setl nolist
        setl textwidth=0
		return "Text Document"
	endif
endfunction
function! IncrementFontSize()
    let g:sessionfontsize+=1
    exec "set guifont=Consolas:h" . g:sessionfontsize . ":cANSI"
endfunction
function! DecrementFontSize()
    let g:sessionfontsize-=1
    exec "set guifont=Consolas:h" . g:sessionfontsize . ":cANSI"
endfunction
" }}}1

"" Keymaps
inoremap jj <Esc>
let mapleader = "\<Space>"
noremap <Leader>w <C-W>
noremap <Leader>ya magg"+yG`a
noremap <F2>		:echo ToggleDocType()<CR>
noremap <F11>		:echo ToggleFullscreen()<CR>
noremap <M-Up>		:silent NERDTree ..\<CR>:setl nolist<CR>:wincmd c<CR>
            \:cd<CR>
noremap <M-Down>	:silent NERDTree %:p<CR>:setl nolist<CR>:wincmd c<CR>
            \:cd<CR>
noremap <leader><M-Down>
            \       :!start explorer /select,%:p<CR>
" CTRL-Z is Undo; not in cmdline though
noremap <F3>		:silent NERDTreeToggle <CR>:wincmd p<CR>
" Alt-up and Alt-down to change cwd
" NOTE: wincmd p instead of c keeps tree open
" Alt-+ Alt-- zoom in and out TODO: do this better, add L and H support
nnoremap <silent> <leader><M-->
            \ :set guifont=Consolas:h2:cANSI<CR>
            \:let &columns = &columns*3<CR>:let &lines = 40+(&lines*2)<CR>
            \:set guioptions+=r<CR>
            \:nnoremap j 10j<CR>
            \:nnoremap k 10k<CR>
nnoremap <silent> <leader><M-=>
            \ :let &columns = &columns/3<CR>:let &lines = (&lines-40)/2<CR>
            \:set guifont=Consolas:h8:cANSI<CR>
            \:set guioptions-=r<CR>
            \:nnoremap j j<CR>
            \:nnoremap k k<CR>
nnoremap <silent> <M--> :echo DecrementFontSize()<CR>
nnoremap <silent> <M-=> :echo IncrementFontSize()<CR>
" Commenting blocks of code.
autocmd FileType c,cpp,java,scala let b:comment_leader = '//'
autocmd FileType sh,ruby,python   let b:comment_leader = '#'
autocmd FileType conf,fstab       let b:comment_leader = '#'
autocmd FileType tex              let b:comment_leader = '%'
autocmd FileType mail             let b:comment_leader = '>'
autocmd FileType vim              let b:comment_leader = '"'
vnoremap <Leader>c :s:^:<C-R>=b:comment_leader<CR> 
            \:<CR>:silent!'<,'>s:^<C-R>=b:comment_leader<CR> <C-R>=b:comment_leader<CR> 
            \:<CR>:noh<CR>`<v`>
nnoremap <Leader>c V:s:^:<C-R>=b:comment_leader<CR> 
            \:<CR>:silent!'<,'>s:^<C-R>=b:comment_leader<CR> <C-R>=b:comment_leader<CR> 
            \:<CR>:noh<CR>`<
" Space-n toggles relative line numbering
nnoremap <Leader>n :set rnu!<CR>:set rnu?<CR>
" Alt-n and N for :cnext :cprev
nnoremap <M-*> *:exec "vim // ".escape(expand("%:p:h"),' ')."/*.*"<CR>
nnoremap <M-n> :cnext<CR>
nnoremap <M-N> :cprev<CR>
" In the help window: Tab and shift-Tab switch between searched topics
" SECTION: Help functions {{{1
function! NextHelp()
    exec "normal :h\<Up>\<CR>"
    if !exists("w:count_help")
        let w:count_help=1
    endif
    if !exists("w:origin_help")
        let w:origin_help="impossiblestring"
    endif
    let w:last_help=strpart(@:,1+match(@:," "))
    if match(w:last_help, w:origin_help)==-1
        let w:origin_help=w:last_help
        let w:count_help=1
    else
        let w:count_help+=1
    endif
    set wcm=<Tab>
    exec "normal :h ".w:origin_help.repeat("\<Tab>",w:count_help)."\<CR>"
endfunction
function! PrevHelp()
    exec "normal :h\<Up>\<CR>"
    if !exists("w:count_help")
        let w:count_help=1
    endif
    if !exists("w:origin_help")
        let w:origin_help="impossiblestring"
    endif
    let w:last_help=strpart(@:,1+match(@:," "))
    if match(w:last_help, w:origin_help)==-1
        let w:origin_help=w:last_help
        let w:count_help=1
    elseif w:count_help>1
        let w:count_help-=1
    endif
    set wcm=<Tab>
    exec "normal :h ".w:origin_help.repeat("\<Tab>",w:count_help)."\<CR>"
endfunction
" }}}1
autocmd BufEnter * silent exec "normal :if &bt=='help'\<CR>nnoremap <buffer> <Tab> :silent echo NextHelp()<CR>\<CR>endif\<CR>"
autocmd BufEnter * silent exec "normal :if &bt=='help'\<CR>nnoremap <buffer> <s-Tab> :silent echo PrevHelp()<CR>\<CR>endif\<CR>"
" Extra Cursor Half-Screen Movement
nnoremap <silent> H :silent if winline() != 1<CR>
            \normal! H<CR>else<CR>
            \exec "normal ".
            \"zz"<CR>
            \end<CR><CR>
"             \string((winheight(winnr())==1)+winheight(winnr())/2)."kzz"<CR>
nnoremap <silent> L :silent if winline() != winheight(winnr())<CR>
            \normal! L<CR>else<CR>
            \exec "normal ".
            \"zz"<CR>
            \end<CR><CR>
"             \string((winheight(winnr())==1)+winheight(winnr())/2)."jzz"<CR>
" nnoremap <silent> L :silent if winheight(winnr()) != winline()<CR>
"             \normal! L<CR>else<CR>normal zzM<CR>end<CR><CR>

"" Plugins
execute pathogen#infect()
"autocmd vimenter * NERDTree | setl nolist
"autocmd VimEnter * wincmd p
let NERDTreeDirArrows=1
let NERDTreeWinSize=24
let NERDTreeChDirMode=2

" YouCompleteMe
"let g:ycm_global_ycm_extra_conf = 'path to .ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_register_as_syntastic_checker = 0

"" vim: set fdm=marker:
