#!/bin/bash

DATE_SPEC="%d/%m"
TIME_SPEC="%H:%M"
DATE_VALUE=$(date "+ $DATE_SPEC")


LABEL_ICON=${icon:-$(xrescat i3xrocks.label.time )}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}
echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$DATE_VALUE </span>"

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec /usr/bin/gnome-calendar
fi
