#!/bin/bash

CONNECTION=$(LC_ALL=C nmcli -t connection show --active | awk -F ':' '
{ if($3 == "vpn") {
    vpn_name=$1
  } else if ($3 == "tun"){
    tun_name=$1
  } else if ($3 == "tap"){
    tun_name=$1
  }
}
END{if (vpn_name) {printf("%s", vpn_name)}  else if(tun_name) {printf("%s", tun_name)}}')

LABEL_COLOR=${vpn_label_color:-$(xrescat i3xrocks.label.color)}
VALUE_COLOR="${vpn_color:-$(xrescat i3xrocks.value.color)}"
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font)}

DEFAULT_VPN="ETHZ"

case $BLOCK_BUTTON in
    1) if [[ -z "$CONNECTION" ]]; then
        nmcli con up id $DEFAULT_VPN
      else
        nmcli con down id $DEFAULT_VPN
      fi ;;  # left click
    3) /usr/bin/i3-msg -q exec /usr/bin/gnome-control-center network ;; # right click
esac

CONNECTION=$(LC_ALL=C nmcli -t connection show --active | awk -F ':' '
{ if($3 == "vpn") {
    vpn_name=$1
  } else if ($3 == "tun"){
    tun_name=$1
  } else if ($3 == "tap"){
    tun_name=$1
  }
}
END{if (vpn_name) {printf("%s", vpn_name)}  else if(tun_name) {printf("%s", tun_name)}}')

if [[ -z "$CONNECTION" ]]; then
  #         🖧  
    echo "<span color=\"${LABEL_COLOR}\" font=\"FontAwesome\"></span> <span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"></span>" # full text
    exit 0
else
  #     
    LABEL_COLOR="#7B83F4"
    VALUE_COLOR="#7B83F4"
    echo "<span color=\"${LABEL_COLOR}\" font=\"FontAwesome\"></span> <span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$CONNECTION</span>" # full text
fi

