#!/usr/bin/env python
from Tkinter import Tk, Label, Button

class MyFirstGUI:
    def __init__(self, master):
        self.master = master
        master.title("A simple GUI")

        self.label = Label(master, text="A useless window designed to be made transparent by i3/compton, to serve as an 'empty' container.")
        self.label.pack()

        self.close_button = Button(master, text="Close", command=master.quit)
        self.close_button.pack()

root = Tk(className="pleasemri3makethiswindowtransparent")
my_gui = MyFirstGUI(root)
root.mainloop()
