#!/bin/bash
# Usage: vimcp [cp arguments, -i, --verbose, -u, etc]
# file appears with commands
# save and exit to run copy command
FINDRESULTFILE=$(mktemp)
CMDFILE=$(mktemp)


LINEWIDTH=$(find "$(pwd)" -type f -printf "%p  \n" | wc -L)
find "$(pwd)" -type f -fprintf "$FINDRESULTFILE" "cp $@ %-${LINEWIDTH}p %p\n"
vim "$CMDFILE" --cmd "silent read $FINDRESULTFILE" --cmd "g/^$/d"
# yesno "Copy $(cat $CMDFILE | wc -l) files?" 'y' &&
source $CMDFILE && echo "$(cat $CMDFILE | wc -l) files copied."
