function [CL CD CM] = get_CL_CD_CM(ail_angle,re,incidence,airfoil)

    cmd = 'global a';
    cmd(8) = airfoil(1);
    eval(strcat(cmd,airfoil(2:length(airfoil))));
    
    re = min(max(re,40000),180000);
    incidence       =   min(179.9,rad2deg(incidence));
    ail_angle       =   rad2deg(ail_angle);                     % Javafoil has the following convention: positive aileron angle = aileron down
    ail_angle       =   max(-10,min(10,ail_angle));
    
    ail_angle_min   =   ail_angle       - mod(ail_angle,1);
    ail_angle_max   =   ail_angle_min   + 1;
    r1              =   mod(ail_angle,1);
    
    re_min          =   re              - mod(re,20000);
    re_max          =   min(re_min      + 20000,200000);
    r2              =   mod(re,20000)/20000;
    
    incidence_min   =   incidence       - mod(incidence,1);
    incidence_max   =   incidence_min   + 1;
    r3              =   mod(incidence,1);
    
    index1          =   ail_angle_min   + 16;
    index2          =   re_min/20000    - 1;
    index3          =   incidence_min   + 181;
    
                            
    CL = eval(strcat(airfoil,'(index1,   index2,   index3  ).CL  *(1-r1) *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1,   index2,   index3+1).CL  *(1-r1) *(1-r2) *   r3  +', ...
                     airfoil,'(index1,   index2+1, index3  ).CL  *(1-r1) *   r2  *(1-r3) +', ...
                     airfoil,'(index1,   index2+1, index3+1).CL  *(1-r1) *   r2  *   r3  +', ...
                     airfoil,'(index1+1, index2,   index3  ).CL  *   r1  *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1+1, index2,   index3+1).CL  *   r1  *(1-r2) *   r3  +', ...
                     airfoil,'(index1+1, index2+1, index3  ).CL  *   r1  *   r2  *(1-r3) +', ...
                     airfoil,'(index1+1, index2+1, index3+1).CL  *   r1  *   r2  *   r3;'));
                
	CD = eval(strcat(airfoil,'(index1,   index2,   index3  ).CD  *(1-r1) *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1,   index2,   index3+1).CD  *(1-r1) *(1-r2) *   r3  +', ...
                     airfoil,'(index1,   index2+1, index3  ).CD  *(1-r1) *   r2  *(1-r3) +', ...
                     airfoil,'(index1,   index2+1, index3+1).CD  *(1-r1) *   r2  *   r3  +', ...
                     airfoil,'(index1+1, index2,   index3  ).CD  *   r1  *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1+1, index2,   index3+1).CD  *   r1  *(1-r2) *   r3  +', ...
                     airfoil,'(index1+1, index2+1, index3  ).CD  *   r1  *   r2  *(1-r3) +', ...
                     airfoil,'(index1+1, index2+1, index3+1).CD  *   r1  *   r2  *   r3;'));

    CM = eval(strcat(airfoil,'(index1,   index2,   index3  ).CM  *(1-r1) *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1,   index2,   index3+1).CM  *(1-r1) *(1-r2) *   r3  +', ...
                     airfoil,'(index1,   index2+1, index3  ).CM  *(1-r1) *   r2  *(1-r3) +', ...
                     airfoil,'(index1,   index2+1, index3+1).CM  *(1-r1) *   r2  *   r3  +', ...
                     airfoil,'(index1+1, index2,   index3  ).CM  *   r1  *(1-r2) *(1-r3) +', ...
                     airfoil,'(index1+1, index2,   index3+1).CM  *   r1  *(1-r2) *   r3  +', ...
                     airfoil,'(index1+1, index2+1, index3  ).CM  *   r1  *   r2  *(1-r3) +', ...
                     airfoil,'(index1+1, index2+1, index3+1).CM  *   r1  *   r2  *   r3;'));
    
end